/**
 * Tests for the indexing throughput benchmark harness.
 *
 * Uses a small fixture (10 TS files) to validate BenchmarkResult structure
 * without incurring full benchmark overhead.
 */
import { describe, it, expect, afterEach } from 'vitest';
import { existsSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { generateFixture } from '../fixture-gen.js';
import { runBenchmark } from '../bench-runner.js';
import type { BenchmarkConfig, BenchmarkResult, FixtureConfig } from '../types.js';

function makeTempDir(label: string): string {
  return join(
    tmpdir(),
    `bench-test-${label}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
  );
}

describe('runBenchmark', () => {
  const tempDirs: string[] = [];

  function trackDir(dir: string): string {
    tempDirs.push(dir);
    return dir;
  }

  afterEach(() => {
    for (const dir of tempDirs) {
      if (existsSync(dir)) {
        rmSync(dir, { recursive: true, force: true });
      }
    }
    tempDirs.length = 0;
  });

  it('returns a BenchmarkResult with all required fields', async () => {
    const fixtureDir = trackDir(makeTempDir('fixture'));
    const fixtureConfig: FixtureConfig = {
      languages: { typescript: 10, python: 0, rust: 0, go: 0 },
      locRange: [10, 30],
      nestingDepth: 2,
      outputDir: fixtureDir,
    };
    generateFixture(fixtureConfig);

    const config: BenchmarkConfig = {
      fixtureDir,
      warmupRuns: 0,
      measuredRuns: 1,
    };

    const result = await runBenchmark(config);

    expect(result).toBeDefined();
    expect(typeof result.timestamp).toBe('string');
    expect(result.timestamp.length).toBeGreaterThan(0);
    expect(typeof result.fixture).toBe('string');
    expect(result.indexingThroughput).toBeDefined();
    expect(typeof result.indexingThroughput.filesPerSecond).toBe('number');
    expect(typeof result.indexingThroughput.totalFiles).toBe('number');
    expect(typeof result.indexingThroughput.totalTimeMs).toBe('number');
    expect(result.peakRss).toBeDefined();
    expect(typeof result.peakRss.bytes).toBe('number');
    expect(result.queryLatency).toBeDefined();
    expect(result.queryLatency.getRepositoryOverview).toBeDefined();
    expect(typeof result.queryLatency.getRepositoryOverview.p50).toBe('number');
    expect(typeof result.queryLatency.getRepositoryOverview.p95).toBe('number');
    expect(typeof result.queryLatency.getRepositoryOverview.p99).toBe('number');
    expect(Array.isArray(result.thresholdResults)).toBe(true);
  });

  it('reports positive elapsed time', async () => {
    const fixtureDir = trackDir(makeTempDir('fixture'));
    const fixtureConfig: FixtureConfig = {
      languages: { typescript: 10, python: 0, rust: 0, go: 0 },
      locRange: [10, 30],
      nestingDepth: 2,
      outputDir: fixtureDir,
    };
    generateFixture(fixtureConfig);

    const result = await runBenchmark({
      fixtureDir,
      warmupRuns: 0,
      measuredRuns: 1,
    });

    expect(result.indexingThroughput.totalTimeMs).toBeGreaterThan(0);
  });

  it('reports files indexed count matching the fixture', async () => {
    const fixtureDir = trackDir(makeTempDir('fixture'));
    const totalFiles = 10;
    const fixtureConfig: FixtureConfig = {
      languages: { typescript: totalFiles, python: 0, rust: 0, go: 0 },
      locRange: [10, 30],
      nestingDepth: 2,
      outputDir: fixtureDir,
    };
    generateFixture(fixtureConfig);

    const result = await runBenchmark({
      fixtureDir,
      warmupRuns: 0,
      measuredRuns: 1,
    });

    // totalFiles in result includes source files + package.json (generated by fixture)
    expect(result.indexingThroughput.totalFiles).toBeGreaterThanOrEqual(totalFiles);
  });

  it('cleans up temporary data directories', async () => {
    const fixtureDir = trackDir(makeTempDir('fixture'));
    const fixtureConfig: FixtureConfig = {
      languages: { typescript: 10, python: 0, rust: 0, go: 0 },
      locRange: [10, 30],
      nestingDepth: 2,
      outputDir: fixtureDir,
    };
    generateFixture(fixtureConfig);

    const result = await runBenchmark({
      fixtureDir,
      warmupRuns: 0,
      measuredRuns: 1,
    });

    // The benchmark runner creates its own data dir internally and cleans it up.
    // The result should still be valid after cleanup.
    expect(result.indexingThroughput.totalTimeMs).toBeGreaterThan(0);
    // The fixture dir should still exist (caller owns it)
    expect(existsSync(fixtureDir)).toBe(true);
  });

  it('evaluates threshold results when thresholds are provided', async () => {
    const fixtureDir = trackDir(makeTempDir('fixture'));
    const fixtureConfig: FixtureConfig = {
      languages: { typescript: 10, python: 0, rust: 0, go: 0 },
      locRange: [10, 30],
      nestingDepth: 2,
      outputDir: fixtureDir,
    };
    generateFixture(fixtureConfig);

    const result = await runBenchmark({
      fixtureDir,
      warmupRuns: 0,
      measuredRuns: 1,
      thresholds: {
        maxIndexTimeMs: 60_000,
        maxRssBytes: 1024 * 1024 * 1024,
      },
    });

    expect(result.thresholdResults.length).toBeGreaterThan(0);
    for (const tr of result.thresholdResults) {
      expect(typeof tr.metric).toBe('string');
      expect(typeof tr.actual).toBe('number');
      expect(typeof tr.threshold).toBe('number');
      expect(typeof tr.passed).toBe('boolean');
    }
  });
});
